---
downloads: ~/.ansible-downloads/

configure_dotfiles_1: true
configure_dotfiles_2: true
configure_terminal: true
configure_oh_my_zsh: true
configure_krew: true
configure_sudoers: false
configure_ssh: true
configure_osx: true
configure_dock: false

oh_my_zsh_write_zshrc: false

# Set to 'true' to configure the Dock via dockutil.
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - News
  - Music
  - Notes
  - Reminders
  - Contacts
  - Calendar
  - FaceTime
  - Photos
  - Maps
  - Mail
  - Messages
  - Safari
  - Freeform

# dockitems_persist:
#   - name: "iTerm"
#     path: "/Applications/iTerm.app/"
#     pos: 1
#   - name: "System Settings"
#     path: "/Applications/System Settings.app/"
#     pos: 2

sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo_1: https://github.com/Y0sh1dk/dotfiles.git
dotfiles_repo_accept_hostkey_1: true
dotfiles_repo_local_destination_1: ~/Code/github/Y0sh1dk/dotfiles
dotfiles_files_1:
  - .zshrc
  - .zlogin
  - .p10k.zsh
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .functions
  - .aliases
  - com.googlecode.iterm2.plist
  - wallpaper.jpg

dotfiles_repo_2: https://github.com/Y0sh1dk/anz-dotfiles.git
dotfiles_repo_accept_hostkey_2: true
dotfiles_repo_version_2: main
dotfiles_repo_local_destination_2: ~/Code/github/Y0sh1dk/anz-dotfiles
dotfiles_files_2:
  - .anz
  - .gitconfig
  - .git-templates
  - .config/1Password
  - .ssh/config

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh
  - pokemonsay
  - git-extras
  - gomplate
  - kubectl
  - kubectx
  - krew
  - helm
  - helmfile
  - skaffold
  - htop
  - jq
  - yq
  - k9s
  - minikube
  - neovim
  - ansible-lint
  - shfmt
  - fortune
  - tfenv
  - tflint
  - terraform-docs
  - checkov
  - awscli
  - kind
  - argocd
  - consul
  - hcl2json
  - go-task
  - linkerd
  - thanos
  - samuong/alpaca/alpaca
  - kustomize
  - oniguruma
  - fluxcd/tap/flux

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - possatti/possatti
  - samuong/alpaca

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - slack
  - iterm2
  - visual-studio-code
  - spotify
  - 1password
  - rectangle
  - stats
  - meld
  - postman
  - todoist
  - 1password-cli
  - temurin
  - goland
  - google-cloud-sdk

# Krew
krew_indexes:
  - name: default
    url: https://github.com/kubernetes-sigs/krew-index.git
  - name: awesome-kubectl-plugins
    url: https://github.com/ishantanu/awesome-kubectl-plugins.git

krew_plugins:
  - access-matrix
  - awesome-kubectl-plugins/node-shell
  - awesome-kubectl-plugins/mtail
  - kuttl

# vs code
vscode_extensions:
  - ms-python.python
  - redhat.ansible
  - hashicorp.terraform
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - redhat.vscode-yaml
  - esbenp.prettier-vscode
  - dbaeumer.vscode-eslint
  - ms-azuretools.vscode-docker
  - eamodio.gitlens
  - pkief.material-icon-theme
  - formulahendry.auto-rename-tag
  - christian-kohler.path-intellisense
  - golang.go
  - wholroyd.jinja
  - oderwat.indent-rainbow
  - mhutchie.git-graph
  - mikestead.dotenv
  - ms-vscode.vscode-typescript-next
  - foxundermoon.shell-format
  - timonwong.shellcheck
  - actboy168.tasks
  - yoavbls.pretty-ts-errors
  - wix.vscode-import-cost
  - casualjim.gotemplate
  - github.vscode-github-actions
  - ms-vscode.makefile-tools

vscode_extensions_absent: []

vscode_settings: {
    # "editor.rulers": [80, 100, 120],
    "editor.renderWhitespace": "all",
    "window.zoomLevel": 1,
    "[yaml]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
    "[jsonc]": { "editor.defaultFormatter": "esbenp.prettier-vscode" },
    "editor.formatOnSave": true,
    "gitlens.codeLens.enabled": false,
    "http.proxyStrictSSL": false,
    "indentRainbow.indicatorStyle": "light",
    "indentRainbow.lightIndicatorStyleLineWidth": 3,
    "workbench.iconTheme": "material-icon-theme",
  }
vscode_settings_overwrite: true

vscode_keybindings: []
vscode_keybindings_overwrite: true

osx_script: "./.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

go_packages:
  - name: github.com/cweill/gotests/gotests
    version: v1.6.0
  - name: github.com/fatih/gomodifytags
    version: v1.16.0
  - name: github.com/josharian/impl
    version: v1.1.0
  - name: github.com/haya14busa/goplay/cmd/goplay
    version: v1.0.0
  - name: github.com/go-delve/delve/cmd/dlv
    version: latest
  - name: honnef.co/go/tools/cmd/staticcheck
    version: latest
  - name: golang.org/x/tools/gopls
    version: latest

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
