---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: gantsign.oh-my-zsh
  - name: gantsign.visual-studio-code-extensions

collections:
  - name: geerlingguy.mac
