---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  args:
    chdir: "{{ ansible_facts['user_dir'] }}"
  changed_when: false
  register: output
