---
- name: Create 1Password directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.1password"
    state: directory

- name: Create symlink for 1Password ssh-agent socket
  file:
    src: "{{ lookup('env', 'HOME') }}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    dest: "{{ lookup('env', 'HOME') }}/.1password/agent.sock"
    state: link

- name: Ensure ssh folder exists
  file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: 0700

- name: Ensure ssh config file exists
  copy:
    content: ""
    dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    force: false

- name: Update ssh config to add 1Password ssh-agent
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.ssh/config"
    marker: "### {mark} ANSIBLE MANAGED BLOCK ###"
    block: |
      Host *
        IdentityAgent "{{ lookup('env', 'HOME') }}/.1password/agent.sock"
