---
- name: Create 1Password directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.1password"
    state: directory

- name: Create symlink for 1Password ssh-agent socket
  ansible.builtin.file:
    src: "{{ ansible_facts['user_dir'] }}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    dest: "{{ ansible_facts['user_dir'] }}/.1password/agent.sock"
    state: link
