---
- name: Get the path to ZSH
  become: false
  command: which zsh
  register: zsh_path

- name: "Ensure homebrew zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: true
    update: true

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: true
    update: true

- name: Install zsh-history-substring-search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search
    clone: true
    update: true
