---
- name: Get the path to ZSH
  become: false
  command: which zsh
  register: zsh_path

- name: "Ensure homebrew zsh is in allowed shells"
  lineinfile:
    path: /etc/shells
    line: "{{ zsh_path.stdout }}"
  become: true

# Plugins
- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    clone: true
    update: true

- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    clone: true
    update: true

- name: Install zsh-history-substring-search
  git:
    repo: https://github.com/zsh-users/zsh-history-substring-search
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search
    clone: true
    update: true

# Theme
- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/themes/powerlevel10k
    clone: true
    update: true

# Fonts
- name: Download powerlevel10k fonts
  git:
    repo: https://github.com/romkatv/powerlevel10k-media
    dest: "/tmp/powerlevel10k-fonts"
    clone: true
    update: true

- name: Install powerlevel10k fonts
  copy:
    src: "/tmp/powerlevel10k-fonts/{{ item }}"
    dest: "/Users/{{ lookup('env', 'USER') }}/Library/Fonts/{{ item }}"
  loop:
    - MesloLGS NF Regular.ttf
    - MesloLGS NF Bold.ttf
    - MesloLGS NF Italic.ttf
    - MesloLGS NF Bold Italic.ttf

# ohmyzsh custom scripts
- name: Install iTerm2-ssh script
  copy:
    src: iTerm2-ssh.zsh
    dest: /Users/{{ lookup('env', 'USER') }}/.oh-my-zsh/custom/iTerm2-ssh.zsh
